### ISSUE TITLE
Combat runs Endless

### ISSUE THREAD

**Issue by RoninCade** [stfc2/Combat#2]
Hi, i installed your Master a few days ago and recompiled the Combat-Deamon.
After i finally got my first Planet i created a second user for testings.

Both users were boosted at the first time.
1st User is Romulan the second one is Cardassian.
Both users got a similar fleet and both fleets are set on red-alert.

When i start a Fleet for attack (the other planet) with "stay in orbit" the Combat-deamon runs endless.
After 30min i killed the Deamon an got an Logbook entry "attacker wins and destroyed the opponent fleet" and the Defenders Logbook show's "attacker defeated and the atackers fleet as been destroyed".
My (attacker) Fleet is still present and now in Orbit of the Defenderplanet.
Re-Attack with "stay in Orbit -> Attacker-Fleet is really destroyed
-no problem with this case, 4 ships against other 4 ships plus heavy orbital defens :-p

But I have no idea to fix case 1.(OuterAttack)
Log-Entry of the moves_tick*.log is:
<font color=#0000ff>Starting <b>Moves Scheduler</b>...</font><br>
entering file<br>
- Moves: Starting process<br>
- Moves Notice: (move_id: 3) AR-User ID is 12<br>
- Moves Notice: (move_id: 3) AR-user(s): <b>1</b><br>
- Moves Notice: (move_id: 3) Entering AR-loop #0<br>
- Moves Notice: (move_id: 3) AR-query:<br>"SELECT f.fleet_id, f.fleet_name, f.n_ships,
                u.user_name AS owner_name
                        FROM (ship_fleets f)
                        INNER JOIN user u ON u.user_id = f.user_id
                        WHERE f.planet_id = 11 AND
                              f.user_id = 12 AND
                              f.alert_phase = 2"<br><br>
- Moves Notice: (move_id: 3) Doing combat in AR-loop #0<br>
... Killing the Process by "kill -9 PID"
- Moves Notice: (move_id: 3) Combat done in AR-loop #0<br>
- Moves Notice: (move_id: 3) Leaving AR-loop #0<br>
- Moves Notice: (move_id: 3) Skipped_action_main()<br>
- Moves Notice: (move_id: 3) Action 26 executed in 393.7488s<br>
- Moves: Ending process<br>

I even resettet the system an disabled the "userboost" option.
INNER or Outer-Attack on a Planet without orbital defens -> Combat-Process has to be killed
So i built 1 small orbital defens on defender Planet.
Attacker Fleet has 9 Frigates.
OuterAttack -> Endless
InnerAttack -> Fleet has been destroyed, without givin damage, like agains Q ^^

Do you have an Idea, whats going wrong?
I just can't find my misstake... -.-

**Comment by kirirur** [comment]
Hello @RoninCade,
sorry for the delay. Have you tried to alter your makefile/config.h files in order to enable verbose output and complie the daemon in simulation mode so you can call it from command line?
It's a good way to test it when something doesn't work as expected.
Typically if the daemon doesn't ends correctly it could be some issue related to the DB interface. Unfortunately it could be that the latest version of the combat daemon is not compatible with the latest version of the DB structure.
I'll check online version of the daemon as soon as I'll have some spare time to spend on it, in the meantime after you have made that test, you can try to downgrade.

**Comment by RoninCade** [comment]
Hi Kirirur,
thanks for response!
So... i did the simulation-mode with verbose = 4..
here the output via commandline:
/opt/stgc2/stgc-moves-combat/bin/moves_combat 5 2 11 0 0 <dbname> <user> <password>

- loaded ship templates:
6 (type:  4/1 values: 55/0/0/115/110/10/17/30/5.2/10/0)
8 (type:  4/1 values: 44/90/0/180/280/17/14/33/8.0/3/16)
10 (type:  4/1 values: 50/90/0/180/280/17/18/36/8.0/3/17)

n_atk: 1/2
n_dfd: 1/2
orbital: 0/0


- atk fleets:
5 (n_ships: 2)

- atk ships:
20 (fleet: 5 xp: 13 hp: 280 units: 25/0/0/2 type: 4/1 rof: 0 torp: 0 values: 51/92/0/180/280/17/18/37/8.0/3/17)
17 (fleet: 5 xp: 13 hp: 280 units: 25/0/0/2 type: 4/1 rof: 0 torp: 0 values: 45/92/0/180/280/17/14/34/8.0/3/16)


- dfd fleets:
2 (n_ships: 2)

- dfd ships:
3 (fleet: 2 xp: 10 hp: 110 units: 20/1/0/3 type: 4/1 rof: 0 torp: 0 values: 55/0/0/115/110/10/17/30/5.2/10/0)
4 (fleet: 2 xp: 10 hp: 110 units: 20/1/0/3 type: 4/1 rof: 0 torp: 0 values: 55/0/0/115/110/10/17/30/5.2/10/0)

* prepare complete, time: 0.020s
<<<<< Stuck

### With small orbital defens
 sudo /opt/stgc2/stgc-moves-combat/bin/moves_combat 5 2 11 0 1 <dbname> <user> <password>

- loaded ship templates:
6 (type:  4/1 values: 55/0/0/115/110/10/17/30/5.2/10/0)
8 (type:  4/1 values: 44/90/0/180/280/17/14/33/8.0/3/16)
10 (type:  4/1 values: 50/90/0/180/280/17/18/36/8.0/3/17)

n_atk: 1/2
n_dfd: 1/2
orbital: 0/1

- atk fleets:
5 (n_ships: 2)

- atk ships:
20 (fleet: 5 xp: 13 hp: 280 units: 25/0/0/2 type: 4/1 rof: 0 torp: 0 values: 51/92/0/180/280/17/18/37/8.0/3/17)
17 (fleet: 5 xp: 13 hp: 280 units: 25/0/0/2 type: 4/1 rof: 0 torp: 0 values: 45/92/0/180/280/17/14/34/8.0/3/16)

- dfd fleets:
2 (n_ships: 2)

- dfd ships:
3 (fleet: 2 xp: 10 hp: 110 units: 20/1/0/3 type: 4/1 rof: 0 torp: 0 values: 55/0/0/115/110/10/17/30/5.2/10/0)
4 (fleet: 2 xp: 10 hp: 110 units: 20/1/0/3 type: 4/1 rof: 0 torp: 0 values: 55/0/0/115/110/10/17/30/5.2/10/0)

* prepare complete, time: 0.020s
* process complete, time: 0.002s
* finish complete, time: 0.000s
### END

Thanks for helping.
I stay tuned, and take a look at the sources ^^

**Comment by kirirur** [comment]
Hello @RoninCube, after the output "prepare process finished" there was no further output?

Have you tried to set verbose level to 5 or more? I don't remember how many levels there are. 

Let me know.

**Comment by RoninCade** [comment]
Hi Kirirur, no futher output after this line...

part of my defines.hh
// ------------- Configuration Macros -------------

// This constant indicates the output level to the scheduler.
// NOTE: ONLY WITH VERBOSE = 0 THE BINARY CAN BE USED IN THE PHP SCHEDULER !
//
//	0 = only expenditures for status and compact combat result, for php schedulers
//	1 = normal mode for standalone operation, detailed information and human-readable
//	2 = normal display with time measurements
//	3 = detailed display for standalone operation and fight details
//	4 = additionally output  for fleets / ships / templates listed before calculate
#define VERBOSE 0-4 (tried each... recompiling... cmdline-test)

// This constant sets the scheduler in simulation mode, in
// which he NO CHANGES STORED.
#define SIMULATOR
// -------- end of part
The output example is with verbose = 4 ..

Could you tell me what the "rof" in the ship-def stand for?
( 20 (fleet: 5 xp: 13 hp: 280 units: 25/0/0/2 type: 4/1 rof: 0 torp: 0 values: 51/92/0/180/280/17/18 )

I just remember an Issue while saving ship-templates..
filed rof was not existent in the db-structure...
whatever, think that's not the problem.

**Comment by kirirur** [comment]
Hi @RoninCube, there is also verbose level 5 despite not being listed in define.hh, trust me. :)

ROF stands for Rate of Fire, it means how many torpedoes in a row a ship can launch. The more the ROF the higher the chance to inflict damage but also lower time for ammunition depletion.

**Comment by RoninCade** [comment]
Hi Kirirur, trustfully change to 5 ;-)
same.. stuck with "prepare complete, time: 0.020s"

but with orbital defens.. wow ^^ pretty nice 

My first idea was, that something is wrong configured in the makefile.. but that should affect the fight with orbital defens too .. or?

**Comment by kirirur** [comment]
Hi, @RoninCube,

You helped me to remember one thing that happened to me some years ago: which kind of platform are you using? The makefle contains some optimisations that are platform dependent, I remember one occasion that while trying to execute the daemon without altering the makefile that causes the process to crash. 

Try to remove all the optimisation from the makefile, it could be something like that.

I need then to remember what comes after that output... But I can't at this moment.

**Comment by Kail72** [comment]
Hi there,

depending on the version of combat you are working on, RoF have to be
greater than zero or no shots will be fired. Orbital guns have RoF
hardcoded so it seems they are the only ships firing and winning the battle.

2015-04-28 15:06 GMT+02:00 Andrea Carolfi <notifications@github.com>:

**Comment by RoninCade** [comment]
Hi Kirirur and hi Kail72,

ROF... and I asked.... nooooo...

The winner is Kail72!

After updating the shiptemplates and ships with rof=1 the fight works in simulation mode...
OMG .. the answer was directly in the output... shame on me... sorry guys ^^

At least i met two new friends ;-p

**Comment by RoninCade** [comment]
hmpf, maybe ofTopic but, this issue result of creating ship-templates right?
so there is a missing value for ROF by creating ships or their template?

**Comment by RoninCade** [comment]
Changes woriking fine, ship_template.php is changed für ROF and ROF2.. 
Thanks a lot Kirirur and Kail72!!!!

**Comment by kirirur** [comment]
Hmm yes, there are some code not correctly aligned. Last version of the DB ha ROF field with default value set to 1, last version of the combat daemon assume one ROF, but last version of UI/ship_template.php has two ROF! It's strange it didn't rise an error while trying to insert a template into the DB...

**Comment by RoninCade** [comment]
Oh, i had a problem to save ship-templates, nothing happend and template wasn't saved.
So i took a look to the error-log:
something like: Unknown field `rof`... and `rof`
I made a diff to the friedegg-version and thought, that this is maybe just an test-flag or whatever and added it..

Just remembered the situation by looking at the combat-output..

**Comment by kirirur** [comment]
Reslly? No DB error message? :o Probably some not checked function.

**Comment by kirirur** [comment]
May I close this issue now?

**Comment by RoninCade** [comment]
ah sorry

combat works fine so far... thx
